S <- c("math", "algebra", "geometry", "calculus", "equations", "computation", "numbers", "addition")
T <- c("poetry", "art", "dance", "literature", "novel", "symphony", "drama", "sculpture")
A <- c("male", "man", "boy", "brother", "he", "him", "his", "son")
B <- c("female", "woman", "girl", "sister", "she", "her", "hers", "daughter")

test_that(".guess errors and integration with query", {
    expect_error(.guess())
    expect_error(.guess(w = googlenews))
    expect_error(.guess(w = googlenews, S = S))
    expect_error(.guess(w = googlenews, S = S, T = T))
    expect_error(.guess(w = googlenews, A = A))
    expect_error(.guess(w = googlenews, S = S, B = B))
    expect_error(.guess(w = googlenews, B = B))
    expect_error(.guess(w = googlenews, T = T))
    expect_error(.guess(w = googlenews, S = S, T = T, A = A, B = B, method = "whatever"))
    expect_error(query())
    expect_error(query(w = googlenews))
    expect_error(query(w = googlenews, S = S))
    expect_error(query(w = googlenews, S = S, T = T))
    expect_error(query(w = googlenews, A = A))
    expect_error(query(w = googlenews, S = S, B = B))
    expect_error(query(w = googlenews, B = B))
    expect_error(query(w = googlenews, T = T))
    expect_error(query(w = googlenews, S = S, T = T, A = A, B = B, method = "whatever"))
})

test_that("guessing and integration with query", {
    expect_equal("mac", .guess(w = googlenews, S = S, A = A))
    expect_equal("mac", .guess(w = googlenews, S = S, A = A, method = "mac"))
    expect_equal("rnd", .guess(w = googlenews, S = S, A = A, B = B))
    expect_equal("rnd", .guess(w = googlenews, S = S, A = A, B = B, method = "rnd"))
    expect_output(.guess(w = googlenews, S = S, A = A, B = B, verbose = TRUE))
    expect_equal("semaxis", .guess(w = googlenews, S = S, A = A, B = B, method = "semaxis"))
    expect_equal("weat", .guess(w = googlenews, S = S, T = T, A = A, B = B))
    expect_equal("weat", .guess(w = googlenews, S = S, T = T, A = A, B = B, method = "weat"))
    expect_equal("rnd", .guess(w = googlenews, S = S, T = T, A = A, B = B, method = "rnd"))
    expect_equal("rnsb", .guess(w = googlenews, S = S, T = T, A = A, B = B, method = "rnsb"))
    expect_equal("nas", .guess(w = googlenews, S = S, T = T, A = A, B = B, method = "nas"))
    expect_true("mac" %in% class(query(w = googlenews, S = S, A = A)))
    expect_true("mac" %in% class(query(w = googlenews, S = S, A = A, method = "mac")))
    expect_true("rnd" %in% class(query(w = googlenews, S = S, A = A, B = B)))
    expect_true("rnd" %in% class(query(w = googlenews, S = S, A = A, B = B, method = "rnd")))
    expect_output(query(w = googlenews, S = S, A = A, B = B, verbose = TRUE))
    expect_true("semaxis" %in% class(query(w = googlenews, S = S, A = A, B = B, method = "semaxis")))
    expect_true("weat" %in% class(query(w = googlenews, S = S, T = T, A = A, B = B)))
    expect_true("weat" %in% class(query(w = googlenews, S = S, T = T, A = A, B = B, method = "weat")))
    expect_true("rnd" %in% class(query(w = googlenews, S = S, T = T, A = A, B = B, method = "rnd")))
    expect_true("rnsb" %in% class(query(w = googlenews, S = S, T = T, A = A, B = B, method = "rnsb")))
    expect_true("nas" %in% class(query(w = googlenews, S = S, T = T, A = A, B = B, method = "nas")))
})
