// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cpp_g
double cpp_g(const String& c, CharacterVector& A, CharacterVector& B, NumericMatrix& glove_mat);
RcppExport SEXP _sweater_cpp_g(SEXP cSEXP, SEXP ASEXP, SEXP BSEXP, SEXP glove_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const String& >::type c(cSEXP);
    Rcpp::traits::input_parameter< CharacterVector& >::type A(ASEXP);
    Rcpp::traits::input_parameter< CharacterVector& >::type B(BSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type glove_mat(glove_matSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_g(c, A, B, glove_mat));
    return rcpp_result_gen;
END_RCPP
}
// cpp_bweat
NumericVector cpp_bweat(CharacterVector& C, CharacterVector& A, CharacterVector& B, NumericMatrix& glove_mat, bool debug);
RcppExport SEXP _sweater_cpp_bweat(SEXP CSEXP, SEXP ASEXP, SEXP BSEXP, SEXP glove_matSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector& >::type C(CSEXP);
    Rcpp::traits::input_parameter< CharacterVector& >::type A(ASEXP);
    Rcpp::traits::input_parameter< CharacterVector& >::type B(BSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type glove_mat(glove_matSEXP);
    Rcpp::traits::input_parameter< bool >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_bweat(C, A, B, glove_mat, debug));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sweater_cpp_g", (DL_FUNC) &_sweater_cpp_g, 4},
    {"_sweater_cpp_bweat", (DL_FUNC) &_sweater_cpp_bweat, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_sweater(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
