# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_g <- function(c, A, B, glove_mat) {
    .Call(`_sweater_cpp_g`, c, A, B, glove_mat)
}

cpp_bweat <- function(C, A, B, glove_mat) {
    .Call(`_sweater_cpp_bweat`, C, A, B, glove_mat)
}

cpp_mac <- function(C, A, glove_mat) {
    .Call(`_sweater_cpp_mac`, C, A, glove_mat)
}

cpp_exact <- function(union_diff, test_stat, s_length) {
    .Call(`_sweater_cpp_exact`, union_diff, test_stat, s_length)
}

